### ISSUE TITLE
Update stack to latest spec

### ISSUE THREAD

**Issue by lukeweber** [crossplane/app-wordpress#11]
Per spec and inflight changes to be merged:
https://github.com/crossplaneio/crossplane/pull/772/files

* `links` is no longer a map of links -> `website`, `source` now fields
* `description` -> `readme`
*  Added:  `overviewShort` - one sentence description
*  Added: `overview` - multi line, but relatively short abstract about the stack

**Comment by displague** [comment]
Thanks for the report @lukeweber!

Closed by crossplaneio/sample-stack-wordpress#8 and crossplaneio/sample-stack-wordpress#14
