### ISSUE TITLE
Use of untyped CR object

### ISSUE THREAD

**Issue by muvaf** [crossplane/app-wordpress#16]
I see that we're using raw template here and populate it via the template engine https://github.com/crossplaneio/sample-stack-wordpress/blob/master/controllers/wordpressinstance_controller.go#L66

Why not just import the type and work on the typed struct? @suskin I can open a PR for this.

**Comment by displague** [comment]
This issue started from the following conversation: https://crossplane.slack.com/archives/CEG3T90A1/p1572590663091500

An additional feature of this repository would be that we _would_ "have an example of using Crossplane API with Go to programmatically create resources".

**Comment by suskin** [comment]
Thanks @muvaf ! Either one is fine; I would go with whichever is more representative of what people creating their own stacks would be doing. The templates **are** a bit of a pain to maintain, so using the type directly could be a good improvement.

How would the dependencies work? It [seems](https://github.com/crossplaneio/crossplane/blob/1217816c2adb582dfb9ff53ee56e54a160cc59f4/apis/workload/v1alpha1/types.go) like we'd need to depend on the whole Crossplane codebase just to work with the types, and I'm not a huge fan of that.

**Comment by muvaf** [comment]
> It seems like we'd need to depend on the whole Crossplane codebase just to work with the types

@suskin There will be a dependency to https://github.com/crossplaneio/crossplane repo but I'm not sure what you mean by _whole Crossplane_.

When you import https://github.com/crossplaneio/crossplane/blob/1217816c2adb582dfb9ff53ee56e54a160cc59f4/apis/workload/v1alpha1/types.go you do depend on it and need to deal with versioning but if you mean the things that you have to download, it's not the whole codebase. It's only the package `github.com/crossplaneio/crossplane/apis/workload/v1alpha1`

**Comment by suskin** [comment]
> it's not the whole codebase. It's only the package

Awesome. Yeah, that's what I wasn't sure about. Thanks for explaining!
