### ISSUE TITLE
Enhance WordpressInstance scheduling capabilities

### ISSUE THREAD

**Issue by hasheddan** [crossplane/app-wordpress#26]
## Current Functionality

There are currently two ways to provision and schedule Wordpress to a Kubernetes cluster:
1. Use a `kubernetesClusterRef` and reference an existing `KubernetesCluster` claim in your namespace for Wordpress to be scheduled to.
2. Omit `kubernetesClusterRef` and the Wordpress controller will create a `KubernetesCluster` for you and default to an available k8s cluster class.

## Proposal

Essentially, we want to enable the following three scenarios:
1. A `KubernetesTarget` already exists in the namespace my `WordpressInstance` is being deployed into and I want to be scheduled to it directly, but there is not a `KubernetesCluster` claim (i.e. it was a manually created `KubernetesTarget`).
2. One or more `KubernetesTarget` exists in my namespace, and I want to be scheduled to one of them.
3. I want to dynamically provision a new k8s cluster by creating a new `KubernetesCluster` in my namespace.

## Implementation

Implementation would involve modifying the `WordpressInstance` CRD in the following manner:
1. Remove `kubernetesClusterRef` field from `spec`.
2. Add `kubernetesTargetRef` field to `spec`
3. Add `provisionNewCluster` field to `spec`.

The behavior of the controller would be altered as follows:
1. If `provisionNewCluster: true` is provided, `kubernetesTargetRef` is ignored and a new `KubernetesCluster` claim is created in the namespace in the same manner as it is currently if `kubernetesClusterRef` is omitted.
2. If `provisionNewCluster` is omitted and `kubernetesTargetRef` is provided with the name of an existing `KubernetesTarget` in the namespace, then Wordpress will be scheduled to that `KubernetesTarget`.
3. If both `provisionNewCluster` and `kubernetesTargetRef` are omitted, the Wordpress controller will default to one of potentially many `KubernetesTarget` instances in the namespace for scheduling.

## Potential Further Enhancement

We could replace (or add as an option) the `kubernetesTargetRef` with `kubernetesTargetSelector` then just propagate the `matchLabels` to the `targetSelector` on the `KubernetesApplication` and then let its scheduler handle it from there.

/cc @prasek @muvaf @suskin

**Comment by prasek** [comment]
@hasheddan thanks for writing this up. overall lgtm, but 1 minor nit: would call out that `provisionNewCluster` can omitted or set to false.

@rathpc does the current [proposed ui metadata](https://github.com/crossplaneio/crossplane/blob/master/design/one-pager-stack-ui-metadata.md#proposed-ui-elements) support conditional fields (e.g. if `provisionNewCluster` is set to false, then show an additional UI field `kuberenetesTargetRef` which could be omitted (schedule to any available `KubernetesTarget`), or set to one of the potentially multiple `KubernetesTarget` CRs in the same workspace / namespace. This ui metadata would need to identify the datasource to use for the list and likely a map function to generate the displayName/value that would be populated into UI control to select the desired `KubernetesTarget`.

**Comment by rathpc** [comment]
@prasek this is the current upbound ui spec definition that was just merged
https://github.com/crossplaneio/crossplane/blob/master/design/design-doc-upbound-ui-spec.md

It does not currently support conditional driven field display or requirement.

**Comment by hasheddan** [comment]
@prasek I don't think that the conditional display has to be in place for this to work (you can show all fields and a user can choose what to populate just like if they were creating the CR directly), nor do I think that this design should be optimized for one organization's UI spec. We should go with the optimal functionality for deploying Wordpress and let any downstream consumers adjust accordingly.

**Comment by displague** [comment]
> If provisionNewCluster: true is provided, kubernetesTargetRef is ignored and a new KubernetesCluster claim is created in the namespace in the same manner as it is currently if kubernetesClusterRef is omitted.

`provisionNewCluster`, if only by name, sounds imperative not declarative.
I see this field intending to act like a reverse `ReclaimPolicy`.

`ProvisionPolicy: Provision | IfNotExist | Never`?

**Comment by hasheddan** [comment]
@displague I think that is definitely a fair point. I like the idea of a `ProvisionPolicy`. It also provides the additional functionality with `IfNotExist` of saying "if there is not a suitable `KubernetesTarget` present in my `Namespace`, please create a new cluster that is suitable". @prasek does this approach fit the functionality you have in mind?

**Comment by prasek** [comment]
@hasheddan @displague good idea. 

For `Never` we'd need the option to pass `kubernetesTargetRef` and users can query the available `KubernetesTargets` in the workspace the app is being deployed to. If no `kubernetesTargetRef` then it will randomly schedule to any available target, so if there's only 1 `KubernetesTarget` in the namespace then they could safely omit `kubernetesTargetRef`.

For `Provision` what query would a user run to show the list of suitable `ResourceClasses` so the user can pick the appropriate `ResourceClass` to use when using `Provision`? Do we need an additional field to allow selecting the resource class by name, e.g. `kubernetesClusterClass` so it isn't randomly selected from the available classes?

For `IfNotExist` we'd need to require both `kubernetesClusterClass` and `kubernetesTargetRef` since it could be either. Does that make sense?

**Comment by prasek** [comment]
@hasheddan @displague So thinking more about this, is `IfNotExists` only handled at initial provisioning time? If so the user should be able to query the list of available `KubernetesTargets` in the same namespace and see if they exist or not and pick an appropriate one, so maybe we can hold off on the `IfNotExists` enum option for the time being and just start with `ProvisionPolicy: ProvisionNewCluster | UseExistingCluster`, and then add `IfNotExists` later if users are looking for that option. Seems like it adds additional complexity which may not be needed right now.

Also, would prefer to use `Provision | UseExistingTarget` to `Provision | Never` since `Never` doesn't imply that the workload will be scheduled to `kubernetesTargetRef`.

**Comment by muvaf** [comment]
I thought about this issue for a while and I think as an app developer, we're forced to make infrastructure decisions here. But as the Wordpress stack developer, I don't really care whether it's a new cluster or not. That's more like infra-operator's decision.

Not blocking any effort here, but in the long term I think we'd want to tackle this and similar problems via https://github.com/crossplaneio/crossplane/issues/1229

**Comment by hasheddan** [comment]
Further discussion has led us to move forward in the following direction:
- Remove `kubernetesClusterRef` field
- Add `provisionPolicy` field which is `*string` enum with possible values `ProvisionNewCluster | UseExistingTarget`
- If `provisionPolicy: ProvisionNewCluster` or the field is omitted, a `KubernetesCluster` claim will be created in the namespace of the `WordpressInstance` (this is essentially the behavior when omitting `kubernetesClusterRef` currently)
- If `provisionPolicy: UseExistingTarget` then the Wordpress `KubernetesApplication` will be created without any `targetSelector -> matchLabels` fields, meaning it will be scheduled at random to a `KubernetesTarget` in the namespace of the `WordpressInstance`

It is my understanding that when this controller is ported to a template stack that this same functionality should be possible, which is one of the determinants of pursuing this strategy.

**Comment by prasek** [comment]
> It is my understanding that when this controller is ported to a template stack that this same functionality should be possible, which is one of the determinants of pursuing this strategy.

//cc @muvaf

**Comment by muvaf** [comment]
@hasheddan yes that should work in template stacks. It'll be an helm chart and we can have an `if` condition that will make the decision of deploying a new `KubernetesCluster` based on a field.
