### ISSUE TITLE
Convert sample-stack-wordpress to a Template Stack and publish to registry

### ISSUE THREAD

**Issue by prasek** [crossplane/app-wordpress#28]
### Overview

Once we have template stacks to the point where we have the minimal gcp stack running on top of template stacks, we'll also want a version of the wordpress stack running on top of template stacks and published to the registry.

It seems like it'd still be useful to have a controller-based wordpress stack, unless we decide to deemphasize controller-based stacks entirely. So this would probably look like a wordpress stack running on top of template stacks as the default sample stack that we point people to, with the controller-based wordpress stack as something that people can look at if they have an advanced use-case.

**Comment by muvaf** [comment]
In Upbound Dev, [Wordpress Stack](https://github.com/crossplane/sample-stack-wordpress) is published to registry and I confirmed that it's working with minimal gcp template stack. @prasek please reopen if you think there is more to do in this issue.
